### ISSUE TITLE
[Bug] SDK `openbb.crypto.load` - when `--source = CCXT`, `start_date` argument makes the function fail.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3380] opened 2022-11-10 22:59 UTC
![Screenshot 2022-11-10 at 2 52 19 PM](https://user-images.githubusercontent.com/85772166/201222823-35ee06f2-3920-45cb-9532-20c230c658aa.png)

![Screenshot 2022-11-10 at 2 53 38 PM](https://user-images.githubusercontent.com/85772166/201222975-887db67b-5903-4b56-9ecc-e3ea051fb229.png)

Works in the Terminal, not through the SDK

![Screenshot 2022-11-10 at 2 56 56 PM](https://user-images.githubusercontent.com/85772166/201223463-3a2454b9-1430-4fba-afa2-a7bcb2072f6b.png)

**Comment by jmaslek** [comment] 2022-11-15 01:09
idk whats up, but i dont reproduce this

<img width="723" alt="Screen Shot 2022-11-14 at 8 09 27 PM" src="https://user-images.githubusercontent.com/18151143/201801655-e5102e61-8e43-45ff-90a8-7c7a4788dc0b.png">

**Comment by hjoaquim** [comment] 2022-11-16 15:54
Can't reproduce either:

![image](https://user-images.githubusercontent.com/48914296/202229075-4a48eb44-2d39-4e40-a46b-71933abb8cd4.png)

I'll close this but re-open if necessary!

**Closed by hjoaquim** 2022-11-16 15:54 UTC
Labels: bug, crypto, SDK
