### ISSUE TITLE
[Bug] DCF - in Windows/Docker Environment: 'NoneType' object has no attribute to 'find'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1360] opened 2022-02-14 14:37 UTC
reported by Discord user: reckinva#3935

Windows/Docker - Discounted Cash Flow: 'NoneType' object has no attribute to 'find'

![image](https://user-images.githubusercontent.com/85772166/153884168-dc87eda5-121e-4c4a-91e9-81e77624748d.png)

**Comment by minhhoang1023** [comment] 2022-02-16 05:22
I was testing and it worked for my Mac. @Chavithra as you have windows, it'd be nice if you could give it a quick try to see if we can reproduce this! 🙌

**Comment by colin99d** [comment] 2022-02-23 17:02
@minhhoang1023 did your PR get merged that fixes this?

**Comment by minhhoang1023** [comment] 2022-02-28 14:49
@colin99d Nope not yet. I wasn't able to reproduce this

**Comment by Chavithra** [comment] 2022-04-04 13:54
I can't reproduce it neither.

@deeleeramone is this issue still there on your setup ?

Thanks

**Comment by piiq** [comment] 2022-04-04 15:27
The docker containers have been updated. The bug is not reproducible anymore 🎉

**Closed by piiq** 2022-04-04 15:27 UTC
Labels: bug
