### ISSUE TITLE
[Bug] - SDK - openbb.stocks.ins.lins - Missed year in Date

### ISSUE THREAD

**Issue by jczernia** [OpenBB-finance/OpenBBTerminal#3608] opened 2022-11-27 10:52 UTC
**Describe the bug**
Date format is wrong, expected MM/DD/YYYY or something like that

**To Reproduce**
call 
traded = openbb.stocks.ins.lins('INTC')
traded.to_csv('INTC.csv', index=True)

see the date format is like 'Nov 16' without year.  Result of print(traded.axes)
[Index(['Nov 16', 'Nov 08', 'Nov 04', 'Oct 31', 'Aug 24', 'May 03', 'May 02',
       'Feb 22', 'Feb 22', 'Feb 02', 'Feb 01', 'Dec 03'],

Note in Windows App date format is MM/DD/YYYY

**Desktop (please complete the following information):**

SDK installed by PyPi openpb 0.0.1
Comparison with Windows installed teminal v1.9.0

**Comment by jczernia** [comment] 2022-11-29 12:32
Issue exists in openbb 2.0.0 installed through pip

**Comment by jmaslek** [comment] 2022-12-06 18:50
So I am digging in and this is actually the response from the finviz library we use (https://github.com/mariostoev/finviz) :
```
import finviz
finviz.get_insider("INTC")
```
This prints out the date format you see here.  If we were to parse this into a date, we would have to add in the year by hand, which may or may not be correct (and this would actualy need to change in a month when they report january data).

In order to get this changed, the best bet would be to open an issue in the finviz library that get_insider() does not return year on the data -- once it is changed there, we can update.

**Comment by d3an** [comment] 2022-12-12 17:24
Hi @jczernia,

This fix for https://github.com/OpenBB-finance/OpenBBTerminal/issues/3608 is more complicated than it might seem, and would likely require a second request per insider transaction. Finviz doesn't provide the year at all, but does provide a link to the respective SEC Form 4, which provides all the necessary details.

A fix in this case would require an additional request to the respective SEC Form 4 per insider transaction (hosted on the SEC's website), which would then be scraped for the necessary details.

Regards,
James

**Comment by colin99d** [comment] 2023-03-20 17:18
I am closing this because the issue is with the data provided by an external API.

**Closed by colin99d** 2023-03-20 17:18 UTC
Labels: bug
