### ISSUE TITLE
[Bug] `reports/equity tsla` Error : 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2833] opened 2022-10-14 08:06 UTC
**Describe the bug**
Equity command gives error.

**To Reproduce**
`python terminal.py reports/equity tsla`

**Screenshots**
<img width="755" alt="Screen Shot 2022-10-14 at 9 06 17 AM" src="https://user-images.githubusercontent.com/72827203/195795587-4266578a-83d0-4dd6-b507-8e2df98d9c54.png">

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by kairosdojo** [comment] 2022-10-14 14:11
Hi! I could reproduce this too. It seems to be an API keys missing (at least in my case). 

The problem is that in [L280 of reports_controller.py](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/reports/reports_controller.py#L280) the `stdout` of the copied notebook is captured, therefore hiding the error.

Disabling that context I got this:

![Screenshot_2022-10-14_16-06-53](https://user-images.githubusercontent.com/22766463/195867553-61efadf7-820f-41c9-9531-9b8bc5243ed2.png)

Probably the lack of API KEYS should be handled.

**Comment by colin99d** [comment] 2022-10-14 14:15
Ok. We should just need better handling of None. Do you want to take this one @kairosdojo?

**Comment by kairosdojo** [comment] 2022-10-14 16:33
Ok, I'll try :)

**Comment by tinix84** [comment] 2022-10-15 21:08
I have the same error but also sometimes other like 
![image](https://user-images.githubusercontent.com/16301528/196007615-3de75e47-1435-459b-a4e1-54cc72c28a71.png)

**Comment by hjoaquim** [comment] 2022-10-15 23:53
@tinix84 in the meantime, #2861 was merged. Would you update and try again pls??

**Closed by hjoaquim** 2022-10-15 23:53 UTC
Labels: bug, notebookreports, HACKTOBERFEST

**Comment by tinix84** [comment] 2022-10-16 06:16
> @tinix84 in the meantime, #2861 was merged. Would you update and try again pls??

I have tried yesterday evening after the update, and I wrote in discord.

**Comment by kairosdojo** [comment] 2022-10-16 06:24
Hello, Riccardo! Maybe it's related to https://github.com/OpenBB-finance/OpenBBTerminal/issues/2860 ? 

What's curious is that your error prints out the cell block number.  

Also, another thing: in my example I had already got an `AAPL.csv` file loaded as a custom dataset; you did just type AAPL (but you hadn't one already saved)?

**Comment by colin99d** [comment] 2022-10-17 07:03
<img width="962" alt="Screen Shot 2022-10-17 at 9 02 25 AM" src="https://user-images.githubusercontent.com/72827203/196110227-87d4a49f-d5ef-47b0-9170-b2643d1bc451.png">
I think this issue is coming from an issue with our OpenBB API? If you haven't recently, could you run `poetry install`. I am unable to reproduce this error in my local code.
