### ISSUE TITLE
[IMPROVE] Add colors when defining a key

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2589] opened 2022-09-22 11:02 UTC
When defining an API key I want to see the output of `defined, test passed` in green, yellow or red. To be easier to understand if my API key was set correctly or not.  I believe this was in place before, but seems got lost somehow

**Comment by catalintoma** [comment] 2022-09-30 17:40
@DidierRLopes I could tackle this when I get some time, but would need better acceptance criteria and context.

First, isn't `defined, test passed` a state of a certain key? How can you want it in multiple colours?

I had a quick look at the history of the **keys_controller** and the logic that choses a colour did not looked to be modified since it was originally built.

Also, I struggled to get into the `defined, test failed` state, I tried dummy keys for both **iExCloud** and **Alphavantage** and they both showed `defined, test passed`, this looks like a bug to me.

**Comment by DidierRLopes** [comment] 2022-09-30 19:03
Hey @catalintoma,

That is correct. I meant having:
```
defined, tested passed - green
defined, unknown test - yellow
defined, test failed - red
not defined - red
```

Interesting, I thought I had added color to it. Might have been my memory tricking me. That looks like a bug to me too. 

Also, we are getting into hacktoberfest, so I recommend you signing up here https://hacktoberfest.com to get some badges and merch for being an open-source contributor 😀

**Comment by montezdesousa** [comment] 2022-09-30 22:17
> @DidierRLopes I could tackle this when I get some time, but would need better acceptance criteria and context.
> 
> First, isn't `defined, test passed` a state of a certain key? How can you want it in multiple colours?
> 
> I had a quick look at the history of the **keys_controller** and the logic that choses a colour did not looked to be modified since it was originally built.
> 
> Also, I struggled to get into the `defined, test failed` state, I tried dummy keys for both **iExCloud** and **Alphavantage** and they both showed `defined, test passed`, this looks like a bug to me.

Hi @catalintoma , I also found the same behavior with the following APIs. I pass a dummy key and get `defined, test passed`.
-> av, fmp, quandl, iex, binance, coinglass, cpanic, smartstake, eodhd.

It should not affect the colors scheme change, but I'll be adding some new architecture to the keys controller so that it can be used in OpenBB SDK, so ping me if you need any help. PR here: https://github.com/OpenBB-finance/OpenBBTerminal/pull/2642

**Comment by catalintoma** [comment] 2022-10-01 15:57
@DidierRLopes I think it was a misunderstanding, what I meant was that there is a colour scheme that wasn't materially changed since you introduced it

I've took a screenshot of all the possible status - colour mappings (notice red is for "anything else".

![image](https://user-images.githubusercontent.com/16468607/193417573-42f56ac5-ffc8-4337-9634-08acda357621.png)

You seem to want "not defined" to map to red and that doesn't seem right to me, majority of users would not want to set every key and red implies a need for action. I think the fact that is grey now is good. 
I don't see anything that we should do now code-wise, correct me if I am wrong.

@montezdesousa nice work you are doing on the OpenBB SDK!
 I've read somewhere that there is an API and will definitely play with it. If I need to do some changes on this bug it is better to move to your branch so we avoid conflicts.

**Comment by DidierRLopes** [comment] 2022-10-01 16:44
> @DidierRLopes I think it was a misunderstanding, what I meant was that there is a colour scheme that wasn't materially changed since you introduced it
> 
> 
> 
> I've took a screenshot of all the possible status - colour mappings (notice red is for "anything else".
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/16468607/193417573-42f56ac5-ffc8-4337-9634-08acda357621.png)
> 
> 
> 
> You seem to want "not defined" to map to red and that doesn't seem right to me, majority of users would not want to set every key and red implies a need for action. I think the fact that is grey now is good. 
> 
> I don't see anything that we should do now code-wise, correct me if I am wrong.
> 
> 
> 
> @montezdesousa nice work you are doing on the OpenBB SDK!
> 
>  I've read somewhere that there is an API and will definitely play with it. If I need to do some changes on this bug it is better to move to your branch so we avoid conflicts.

Yup. That was a mistake on my side. Good catch. Not defined should be grey indeed as the user may not want to play with that source. Red should be "defined, test failed".

**Comment by catalintoma** [comment] 2022-10-03 07:33
Cool `defined, test failed` fits the "other" group so it is red.
I think you can close this as `as designed`

**Comment by DidierRLopes** [comment] 2022-10-04 23:16
This ticket was meant for as soon as you go into the `keys` menu and do something like `av KEY`. IIRC that output never has any colouring.

**Comment by montezdesousa** [comment] 2022-10-05 10:03
@DidierRLopes you mean the string that is displayed on the command line, like this?
![image](https://user-images.githubusercontent.com/79287829/194035111-8a383346-dec6-43bc-b244-60cb9e08f633.png)

**Comment by DidierRLopes** [comment] 2022-10-05 10:43
> @DidierRLopes you mean the string that is displayed on the command line, like this?
> ![image](https://user-images.githubusercontent.com/79287829/194035111-8a383346-dec6-43bc-b244-60cb9e08f633.png)

Exactly!!

**Comment by montezdesousa** [comment] 2022-10-05 12:00
> > @DidierRLopes you mean the string that is displayed on the command line, like this?
> > ![image](https://user-images.githubusercontent.com/79287829/194035111-8a383346-dec6-43bc-b244-60cb9e08f633.png)
> 
> Exactly!!

Check out the `api_keys` branch, should be there now

**Closed** 2024-02-13 22:07 UTC
Labels: enhancement, HACKTOBERFEST
