### ISSUE TITLE
[Bug] vwap function returning list instead of DF

### ISSUE THREAD

**Issue by sergio-abu** [OpenBB-finance/OpenBBTerminal#3967] opened 2023-01-14 19:21 UTC
**Describe the bug**

vwap function returning list instead of DF, this is not intended as seen in the sdk documentation. Error:
AttributeError: 'list' object has no attribute 'plot'

**To Reproduce**
STOCK = openbb.stocks.load('BABA')

VWAP = openbb.ta.vwap(pd.Series(STOCK['Close']))

VWAP.plot()

I want to contribute by adding many more technical indicators and fixing the bugs, but I don't know how to approach that since you guys did not code  the ta's instead i think you guys are using https://github.com/twopirllc/pandas-ta.
Looking for a response, specially on how should I contribute.

**Comment by deeleeramone** [comment] 2023-01-14 19:43
Looks like incorrect syntax. Try it like this instead:


```
openbb.ta.vwap_chart(data = df, symbol = 'BABA')
```

**Comment by sergio-abu** [comment] 2023-01-14 20:47
> Looks like incorrect syntax. Try it like this instead:
> 
> ```
> openbb.ta.vwap_chart(data = df, symbol = 'BABA')
> ```
This works. Can you send me the link for the documentation of pandas-ta? 
The documentation of the sdk is wrong. I will update it

**Comment by deeleeramone** [comment] 2023-01-14 23:08
Closing because not a bug.

`openbb.ta.vwap(df)`

![image](https://user-images.githubusercontent.com/85772166/212500944-280e8a94-6c3b-4481-ba01-5c60a1ffbb42.png)

**Closed by deeleeramone** 2023-01-14 23:08 UTC
Labels: bug

**Comment by sergio-abu** [comment] 2023-01-14 23:29
If its not a bug the documentation is wrong.

**Comment by sergio-abu** [comment] 2023-01-14 23:30
To change it it would be necessary to know the source code

**Comment by deeleeramone** [comment] 2023-01-14 23:37
Which part about it is wrong? It performs exactly as described.

```

    Use 'ta.vwap_chart' to access the view.
    Gets volume weighted average price (VWAP)
    
        Parameters
        ----------
        data: pd.DataFrame
            Dataframe of dates and prices
        offset: int
            Length of offset
        Returns
        -------
        df_vwap: pd.DataFrame
            Dataframe with VWAP data
```

**Comment by sergio-abu** [comment] 2023-01-14 23:37
https://docs.openbb.co/sdk/reference/ta/vwap asks for a series

**Comment by sergio-abu** [comment] 2023-01-14 23:39
it just the type hint

**Comment by deeleeramone** [comment] 2023-01-14 23:44
I see what you mean. The description itself is fine.
