### ISSUE TITLE
[Bug] Sentiment Investor features are dead: Cannot read properties of undefined (reading 'map')"

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2212] opened 2022-07-30 19:14 UTC
With the ticker loaded, GME, this is the output for both `/stocks/ba/trend` and `/stocks/ba/history`

<img width="1327" alt="Screen Shot 2022-07-30 at 12 13 10 PM" src="https://user-images.githubusercontent.com/85772166/181945296-8e24fcc5-90aa-40cb-a73c-c103bdfd6307.png">

**Comment by ricwillis98** [comment] 2022-07-31 15:35
I can't reproduce the trend error above running Python from WSL. The trend function returns a result for me but at first glance it appears to be exclusively cryptos:
![image](https://user-images.githubusercontent.com/62662248/182033355-6ecb348f-d173-4431-8a92-f0addfa67a36.png)

I tried to see if anything equities are supported at all with the "All Supported Tickers" endpoint and unsurprisingly there are no supported equities right now, only cryptos which explains why the hist function doesn't work.

![image](https://user-images.githubusercontent.com/62662248/182033179-d2316223-df15-42d9-b23c-7b35e74f8729.png)

I tried bypassing the supported ticker check and querying anyway to see if it was a bug on their end and I get an unsupported error from the API: 
![image](https://user-images.githubusercontent.com/62662248/182033775-05a21976-56f4-455d-8112-0e4248ff95a4.png)

Seems like a bug or "feature" on their end, perhaps they're moving away from supporting equities on the free tier and forgot to update their docs or something. I'm happy to clean this up to fail a bit more gracefully if needed - let me know how you guys want to handle it.

**Comment by DidierRLopes** [comment] 2022-08-07 23:12
Sorry for the delay on the reply on our end.

Seems like they are moving to crypto only:
<img width="1335" alt="Screenshot 2022-08-08 at 00 11 34" src="https://user-images.githubusercontent.com/25267873/183314692-96b1680b-d5ba-4559-a19d-9697648c424c.png">

Are you ok to remove those 2 commands from the stocks menu? Thanks! 🙏🏽

**Comment by ricwillis98** [comment] 2022-08-08 01:15
Sure, I can remove the commands - will do sometime this week

**Closed** 2022-09-17 03:04 UTC
Labels: bug
