### ISSUE TITLE
[Bug] API - `openbb.stocks.load(symbol = 'SPY, source = 'Polygon')`: AttributeError: 'str' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2793] opened 2022-10-11 19:06 UTC
Error using `load` when `source = 'Polygon'`
```
spy_monthly = openbb.stocks.load(symbol = 'SPY', start_date = '1990-01-01', monthly = True, source = 'Polygon')

AttributeError: 'str' object has no attribute 'strftime'
```

![Screen Shot 2022-10-11 at 12 02 42 PM](https://user-images.githubusercontent.com/85772166/195177429-d94e306c-beb2-438e-bea3-1c9b4d12b5f2.png)

**Comment by colin99d** [comment] 2022-10-14 15:38
I am closing this because it is essentially a duplicate of #2794.

**Closed by colin99d** 2022-10-14 15:38 UTC
Labels: bug
