### ISSUE TITLE
[Bug] Stocks/TA/fib - RuntimeWarning: invalid value encountered

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2675] opened 2022-09-29 16:16 UTC
`/Users/danglewood/GitHub/GST1/miniconda3/envs/obb/lib/python3.9/site-packages/matplotlib/ticker.py:2789:RuntimeWarning: invalid value encountered in log10
  majorstep_no_exponent = 10 ** (np.log10(majorstep) % 1)`

recreate with: 
```
/stocks/load appl/ta/fib
```
<img width="1228" alt="Screen Shot 2022-09-29 at 9 14 17 AM" src="https://user-images.githubusercontent.com/85772166/193083982-93562ffe-3797-4745-bf6c-3d734762ed14.png">

**Comment by colin99d** [comment] 2022-09-30 05:55
I am not able to reproduce this error. Are you on the main branch or the installer?

**Comment by colin99d** [comment] 2022-10-03 07:38
@hjoaquim, are you able to recreate this?

**Comment by erlandsen-tech** [comment] 2022-10-03 07:44
I am not able to recreate this. Conda install, wsl2.

**Comment by hjoaquim** [comment] 2022-10-03 08:43
I can't reproduce, either. Using main branch on ubuntu:
![image](https://user-images.githubusercontent.com/48914296/193535856-f6877198-f14a-4f83-80e7-69f8cd746280.png)

**Comment by DidierRLopes** [comment] 2022-10-04 22:52
@deeleeramone do you still get this?

**Comment by DidierRLopes** [comment] 2022-10-04 22:52
Otherwise, let's close it

**Comment by deeleeramone** [comment] 2022-10-04 22:56
yup. just pulled from main, so still fresh

<img width="1315" alt="Screen Shot 2022-10-04 at 3 56 08 PM" src="https://user-images.githubusercontent.com/85772166/193945465-fefdb16c-1a87-4368-bcab-d9259025d0f0.png">

**Comment by DidierRLopes** [comment] 2022-10-04 23:06
This is not on our side, but in matplotlib.

What version are you using?

**Comment by deeleeramone** [comment] 2022-10-04 23:17
3.5.3

**Comment by DidierRLopes** [comment] 2022-10-05 08:07
I have 3.5.1. Can you try to downgrade? I have an impression this comes with an update of matplotlib

**Comment by colin99d** [comment] 2022-10-05 08:15
I have 3.5.3 and have no errors.

**Comment by colin99d** [comment] 2022-10-17 07:09
I am going to close this for now. I am assuming it has to do with a weird environment configuration. If others are able to reproduce feel free to open.

**Closed by colin99d** 2022-10-17 07:09 UTC
Labels: bug, HACKTOBERFEST
