### ISSUE TITLE
[Bug]------------------------------------------------------------------------- AttributeError                            Traceback (most recent call last) Cell In[75], line 1 ----> 1 openbb.stocks.ba.headlines("TSLA")  AttributeError: module 'openbb' has no attribute 'stocks'

### ISSUE THREAD

**Issue by 13381833071** [OpenBB-finance/OpenBBTerminal#6332] opened 2024-04-23 01:57 UTC
-------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[75], [line 1](vscode-notebook-cell:?execution_count=75&line=1)
----> [1](vscode-notebook-cell:?execution_count=75&line=1) openbb.stocks.ba.headlines("TSLA")

AttributeError: module 'openbb' has no attribute 'stocks'

**Comment by deeleeramone** [comment] 2024-04-24 15:19
Hi there, this is a syntax error. This command and path does not exist.

There's a few details [here](https://docs.openbb.co/platform/faqs/platform_vs_sdk#terminal-application) on the main differences between the legacy architecture and the Platform architecture.

Closing this issue because it is not a bug.

**Closed by deeleeramone** 2024-04-24 15:19 UTC
