### ISSUE TITLE
[Bug] Twitter API key

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#1712] opened 2022-04-18 22:58 UTC
![image](https://user-images.githubusercontent.com/25267873/163890199-7804824e-5375-4eeb-b187-ad30c84aea0a.png)

**Comment by deeleeramone** [comment] 2022-04-20 21:55
I am able to add a Twitter key in the new installer package
```
2022 Apr 20, 17:52 (🦋) /keys/ $ twitter -h
usage: twitter [-k KEY] [-s SECRET_KEY] [-t BEARER_TOKEN] [-h]

Set Twitter API key.

optional arguments:
  -k KEY, --key KEY     Key (default: None)
  -s SECRET_KEY, --secret SECRET_KEY
                        Secret key (default: None)
  -t BEARER_TOKEN, --token BEARER_TOKEN
                        Bearer token (default: None)
  -h, --help            show this help message (default: False)

2022 Apr 20, 17:52 (🦋) /keys/ $ twitter -k keyhash -s secrethash -t AAAAAAAAAAAAAAAAAAAAAreallylongstring
defined, test passed
```
![Screen Shot 2022-04-20 at 2 55 30 PM](https://user-images.githubusercontent.com/85772166/164330767-b39eed45-44ad-4fb5-8d6a-c0e887bac06b.png)

**Comment by Chavithra** [comment] 2022-05-10 19:52
I also can't reproduce this issue.
Closing this ticket.

**Closed by Chavithra** 2022-05-10 19:52 UTC
Labels: bug
