### ISSUE TITLE
[Bug] In Sector and Industry analysis when using StockAnalysis the units aren't taken into account

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#1507] opened 2022-03-18 09:12 UTC
`python terminal.py stocks/load aal/sia/clear country/vis re`

<img width="794" alt="Screenshot 2022-03-18 at 10 10 55" src="https://user-images.githubusercontent.com/25267873/158974058-d39e6511-86eb-47b7-b786-df0d580505b9.png">

**Comment by JerBouma** [comment] 2022-03-18 09:26
What do you mean exactly?

**Comment by DidierRLopes** [comment] 2022-03-18 09:34
ZNH does not have 90B revenue in Dollars but in Chinese Yuan. So this is misleading because Chinese Yuan is much weaker than dollars.
 
<img width="1093" alt="Screenshot 2022-03-18 at 10 33 03" src="https://user-images.githubusercontent.com/25267873/158977704-7d28b92d-8766-483f-93d2-6ed5bc8ce835.png">

**Comment by JerBouma** [comment] 2022-03-18 09:35
Ah got it, I wasn't aware they were making that adjustment as well. Will add options similar to what I have for the Economy menu.

**Comment by DidierRLopes** [comment] 2022-03-18 09:36
Thanks! 😄

**Comment by JerBouma** [comment] 2022-03-18 09:44
@colin99d This also applies to you. All these values are set to dollars while they aren't actually dollars. I think it is less of an issue for you since you don't compare between companies (of different countries) but still the dollar symbols here are incorrect.

![Screenshot 2022-03-18 at 10 43 29](https://user-images.githubusercontent.com/46355364/158979396-2a62f654-9ba7-4b5d-a0da-97040ba80619.png)

**Comment by JerBouma** [comment] 2022-03-18 11:58
So I was able to reproduce the graph with new figures (it now alters the values based on the **median** exchange rate of that specific year) but still some limitations visible due to #151

![Screenshot 2022-03-18 at 12 58 39](https://user-images.githubusercontent.com/46355364/158999220-34919e3d-8b79-4447-a2c1-5e3b78a2091c.png)
4.

**Comment by JerBouma** [comment] 2022-04-04 14:15
This one is fixed in #1518.

**Closed by JerBouma** 2022-04-04 14:15 UTC
Labels: bug
