### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Aloushka** [OpenBB-finance/OpenBBTerminal#4529] opened 2023-03-18 18:59 UTC
**Describe the bug**
I am trying to run the Quote function for spdr_sectors exactly as displayed in the docs, in a 
![openbb-quote](https://user-images.githubusercontent.com/124839343/226130450-1feffeb9-5d2e-4253-bf29-be83ce24801a.jpg)
Jupyter notebook using the OpenBB SDK

https://docs.openbb.co/sdk/guides/intros/stocks#load

**To Reproduce**
```
spdr_sectors = ['SPY', 'XLE', 'XLB', 'XLI', 'XLP', 'XLY', 'XLV', 'XLF', 'XLK', 'XLC', 'XLU', 'XLRE']

quotes: object = []
symbols = spdr_sectors
for symbols in spdr_sectors:
    quote = openbb.stocks.quote(symbols).transpose()
    quotes.append(quote)

quotes = pd.concat(quotes)

quotes
```

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- Windows 10
- Python version [e.g. 3.10]

**Additional context**
Docs specify default is Yahoo finance which does not require API
all other openbb functions such as load work , no issues

**Comment by deeleeramone** [comment] 2023-03-18 20:02
Hi there,

The error says that you have not obtained and set the API key from FinancialModelingPrep.

https://docs.openbb.co/sdk/quickstart/api-keys#financial-modeling-prep

Closing because this is not a bug.

**Closed by deeleeramone** 2023-03-18 20:02 UTC
Labels: bug, guides, jupyterlab, help-wanted
