### ISSUE TITLE
[Bug] - stocks/load error: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by raxosiris** [OpenBB-finance/OpenBBTerminal#3952] opened 2023-01-13 17:56 UTC
**Describe the bug**
Not sure if it's a temporary issue with an API but `stocks/load $ticker` runs into the following error:

```Error: can only concatenate str (not "NoneType") to str```

It's likely one of the variables being concatenated during load is not coming as a string anymore

**To Reproduce**
1. `/stocks`
2. `/load MSFT`

**Screenshots**
<img width="509" alt="image" src="https://user-images.githubusercontent.com/33306256/212387621-07370a26-92ca-4b7d-9b64-5863b0b96d9e.png">

**Desktop (please complete the following information):**

- OS: Ventura 13.1
- Python version 3.10.8

**Comment by jmaslek** [comment] 2023-01-13 18:01
Hey!  This was an issue with yfinance sometime last month that they fixed and we upgraded from.  

If you are running the installer package, update to 2.1

If you are using the local install, make sure that you are up to date (we moved our latest to `develop`) and that you have run poetry install again to install the updated dependencies.

**Comment by raxosiris** [comment] 2023-01-13 18:22
Hey @jmaslek! Double checked and running 2.1 indeed. Still getting the same error. Screenshot below.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/33306256/212391693-43872b3e-b84b-4e94-a363-95ddef0cc8e1.png">

Here's the latest log file output:

```
I|gst_packaged|sha:7e90d20d|a754311d-caa6-4b10-8563-7eacbb8b5c08|1673633878|NA|2023-01-13T18:18:54+0000|openbb_terminal.terminal_controller.TerminalController|switch|0|START
I|gst_packaged|sha:7e90d20d|a754311d-caa6-4b10-8563-7eacbb8b5c08|1673633878|NA|2023-01-13T18:18:54+0000|openbb_terminal.parent_classes|log_cmd_and_queue|303|CMD: {"path": "/", "known_cmd": "stocks", "other_args": "", "input": "stocks"}
I|gst_packaged|sha:7e90d20d|a754311d-caa6-4b10-8563-7eacbb8b5c08|1673633878|NA|2023-01-13T18:18:58+0000|openbb_terminal.stocks.stocks_controller.StocksController|switch|0|START
I|gst_packaged|sha:7e90d20d|a754311d-caa6-4b10-8563-7eacbb8b5c08|1673633878|NA|2023-01-13T18:18:58+0000|openbb_terminal.parent_classes|log_cmd_and_queue|303|CMD: {"path": "/stocks/", "known_cmd": "load", "other_args": "MSFT", "input": "load MSFT"}
E|gst_packaged|sha:7e90d20d|a754311d-caa6-4b10-8563-7eacbb8b5c08|1673633878|NA|2023-01-13T18:18:59+0000|openbb_terminal.stocks.stocks_controller.StocksController|switch|0|Exception: can only concatenate str (not "NoneType") to str MOCKING_BREAKLINE Traceback (most recent call last):\n  File "openbb_terminal/decorators.py", line 68, in wrapper\n    value = func(*args, **kwargs)\n  File "openbb_terminal/parent_classes.py", line 363, in switch\n    getattr(\n  File "openbb_terminal/parent_classes.py", line 1129, in call_load\n    self.add_info = stocks_helper.additional_info_about_ticker(\n  File "openbb_terminal/stocks/stocks_helper.py", line 931, in additional_info_about_ticker\n    extra_info += ticker_stats.get("quoteType", {}).get("shortName")\nTypeError: can only concatenate str (not "NoneType") to str'
```

**Comment by jmaslek** [comment] 2023-01-13 18:33
And you are using the installer?

Todays yf issue is `string indices must be integers`.  The issue you are showing occurs on an old version of yf, so I am confused 😅

**Comment by raxosiris** [comment] 2023-01-13 18:42
Yep, used the installer 😅, and checked with another friend to rule out geo-restriction related error. Are you able to reproduce the issue?

We were able to use it fine yesterday fyi.

Haha, I have not yet encountered today's other yf issue yet. Happy to help with either though just need to get the dev setup ready for obb.

**Comment by jmaslek** [comment] 2023-01-13 18:58
Okay.  So just reproduced this on the installer.   I guess because the installer was built on yf 1.x this occurs, whereas the string error is currently on 2.x

So it is still related to the decryption in yf (tracking here: https://github.com/OpenBB-finance/OpenBBTerminal/issues/3950 )

A completely hacky way to work around would be to do something like

```
economy/index msft --export file.csv/stocks/load msft -f file.csv
```

(You may need to move the file.csv into exports/stocks for that to work)

**Comment by raxosiris** [comment] 2023-01-13 19:43
Ah, thanks for the workaround. Appreciate the prompt responses. I'll get on the develop branch and run from there for now.

**Comment by sergio-abu** [comment] 2023-01-13 20:56
I'm having the exact same problem, installed this week, and it was working fine yesterday. It happens when I try to load a stock, not only from Yahoo Finance but from Alpha Vantage as well (By induction its likely that the others as well). 
@jmaslek is this hacky solution meant to be used on the terminal?
Should the sdk work?

**Comment by jmaslek** [comment] 2023-01-13 21:28
Yeah this is my poor design that when you load in a stock, it grabs certain yf info about the exchange/timezone, independent of the source,  So its technically grabbing the data then failing on the "additional info" no matter the source.

The sdk should not be impacted by this at all.  openbb.stocks.load() does not call yf.info

**Comment by sergio-abu** [comment] 2023-01-13 21:31
Thank you. @jmaslek I found an typing error on sdk documentation, opened a discussion and sent you and email, I know this is not the place but wanted to send you a heads up.

**Comment by alvarocleite** [comment] 2023-01-14 10:22
Same problem here. 
I'm using the docker image with the latest release.

**Comment by jmaslek** [comment] 2023-01-17 23:54
This is fixed on `develop` and will be put out into a new release in the next 24-48 hours

**Closed by jmaslek** 2023-01-17 23:54 UTC
Labels: bug
