### ISSUE TITLE
[Bug]Cannot load stock prices 

### ISSUE THREAD

**Issue by msh855** [OpenBB-finance/OpenBBTerminal#5843] opened 2023-12-01 14:08 UTC
I am using the following code taken from platform's example: 

```

import pandas as pd
from openbb import obb
df_daily = obb.equity.price.historical(symbol = "spy", provider="yfinance")
df_daily.to_df().head(1)

```
But I get this error: 

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/114295360/2f781178-ab20-49c9-b29b-9e7f9ad24b54)

**Comment by jmaslek** [comment] 2023-12-01 14:10
`pip install openbb-yfinance`

**Comment by msh855** [comment] 2023-12-01 14:18
Thanks. It worked, but is getting very confusing 

The documentation needs to be clear on this especially on what we are (or not) installing with `pip install openbb`

**Comment by deeleeramone** [comment] 2023-12-04 23:25
Hi,

I'm closing this issue because it's not a bug.  Feel free to re-open as an Improvement Issue if you think the explanation [here](https://docs.openbb.co/platform/extensions/data_extensions#installation) needs to be expanded on.

**Closed by deeleeramone** 2023-12-04 23:25 UTC

**Comment by msh855** [comment] 2023-12-05 06:04
What is not clear is the symbols. Is it assumed that symbols depend on providers ? So, if I use `yfinance` the symbols of each stock are the tickers from yfinance. Similarly, if use `fmp` as my provider, the symbol for each stock come from `fmp`
