### ISSUE TITLE
[Bug] Uncaught python errors

### ISSUE THREAD

**Issue by pvutov** [OpenBB-finance/OpenBBTerminal#3752] opened 2022-12-10 18:13 UTC
**Describe the bug**
Python error messages show up in the terminal without clarification.

**To Reproduce**
I am on the latest commit (fb667ce), but also observed the bug in an older version.
1. Start the terminal
2. type "stocks"
3. type "load vwce.de"
4. type "dd"
5. type "sec"
6. You should now get the python error message:
```
Error: 'NoneType' object has no attribute 'set_index'

Error: 'list' object has no attribute 'head'
```

**Screenshots**
None

**Desktop (please complete the following information):**

- OS: ArchLinux
- Python 3.9.13
- conda 22.9.0
- commit fb667ce

**Additional context**
I also crashed openbb terminal once with this sequence of commands, but it was on an older commit and I am not able to reproduce it (after one try).

**Comment by deeleeramone** [comment] 2022-12-11 20:54
Interesting edge case. Error handling should be improved to say something like, "This command is for US-listed tickers only."

```
(🦋) /stocks/dd/ $ sec

Error: 'NoneType' object has no attribute 'set_index'

Error: 'list' object has no attribute 'head'
```

**Comment by kjura** [comment] 2022-12-13 21:32
Hiya, is this still opened and not taken by anyone? I'm really keen to dive into the codebase and learn sth. I reckon that this has to do with the lines in marketwatch_model.py and market_watch.py (to be precise: get_sec_filings and sec_filings)?

https://github.com/OpenBB-finance/OpenBBTerminal/blob/fb667ce867d07a39076b158a2aeef8504543920d/openbb_terminal/stocks/due_diligence/marketwatch_model.py#L67-L72

https://github.com/OpenBB-finance/OpenBBTerminal/blob/fb667ce867d07a39076b158a2aeef8504543920d/openbb_terminal/stocks/due_diligence/marketwatch_view.py#L15-L29

Can confirm that I also have the same behaviour:

- OS: Ubuntu
- Python 3.9.15
- conda 4.12.0 (yeah, I know)
- commit https://github.com/OpenBB-finance/OpenBBTerminal/commit/fb667ce867d07a39076b158a2aeef8504543920d


![image](https://user-images.githubusercontent.com/30084359/207444744-05dfe687-8dff-44a3-a35c-fa002b05d9c4.png)

If I hijacked this thread and somebody's already working on this, sorry

**Comment by hjoaquim** [comment] 2022-12-19 16:43
Hey @kjura thank you for taking a look at this!
We're solving the yf issue here: #3801

I'll assign this one to you! If some help is needed fell free to ping me!

**Comment by kjura** [comment] 2022-12-19 19:19
Thanks! I've been waiting for #3796  to be closed, I'm kinda blocked by yf at this point, it occured when I was debugging through marketwatch_model, I guess a simple check for "Sec fillings" field on markewatch will do the trick, a simple query filtered by two attributes linking to financials/secfilings, if it does not exist, return an empty Dataframe with a message explaining the null value.

**Comment by hjoaquim** [comment] 2022-12-21 12:16
@kjura the issue is now closed!

**Comment by kjura** [comment] 2022-12-21 23:03
@hjoaquim Good to hear! I have a question about MVC, namely about the possiblity of fixing this issue, below commits for my fork:

https://github.com/kjura/OpenBBTerminal/blob/a45bda6f8c485ad7d4ed39515b4b1a7ca93fd283/openbb_terminal/stocks/due_diligence/marketwatch_model.py#L45-L50

https://github.com/kjura/OpenBBTerminal/blob/a45bda6f8c485ad7d4ed39515b4b1a7ca93fd283/openbb_terminal/stocks/due_diligence/marketwatch_view.py#L27-L31

I get it that _model.py is allowed to return some value, in this case a dataframe, for _model.py will have a convieniet if, checking if sec filings exists for a given ticker (if outside of US, return the empty frame)

What about _view.py? sec_filings prints the dataframe, but in the case of it being empty? Can we allow for a return None inside _view.py? We need to somehow abort the operation of printing sec filings, return None is quick, but I don't know if this will have a future impact on the codebase

There is also the case of unittests, if _view.py will not have any output (None, nothing to display), should we skip a test for this case?

PS: If I already have a POC in my fork, should I open a PR but mark it as a draft or do you prefer to keep it here, waiting for a green light for PR?

PS2: Current behaviour for specyfing a stock without Sec Filings, message to the user:

![image](https://user-images.githubusercontent.com/30084359/209019396-d1da03d7-ceb7-4d11-a444-d4c2f426eba7.png)

**Comment by hjoaquim** [comment] 2022-12-22 11:37
Hey @kjura !

I would say that returning an empty dataframe is the way - we can always check the emptiness of it in the `_view` (just like you did) if we want to display a custom message like "There is no data available for the selected symbol" (just an example). Returning `None` after this shouldn't be an issue.

Regarding tests, I don't think those should be skiped bc printing an empty string or even a custom message might be the desired behaviour!

Feel free to open a PR and leave it as draft as long as you're working on it! It's much easier to check the differences and ask for feedback / suggestions / doubts!

Thank you :rocket:

**Closed** 2023-01-18 00:10 UTC
Labels: bug
