### ISSUE TITLE
[Bug] OpenBB terminal 3.0.0

### ISSUE THREAD

**Issue by stephaniec2020** [OpenBB-finance/OpenBBTerminal#4913] opened 2023-04-26 21:37 UTC
**Describe the bug**
I installed the openBB terminal 3.0.0 and when I load the terminal, it has an error.

Traceback (most recent call last):
  File "terminal.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/__init__.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/core/plots/__init__.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/core/plots/plotly_helper.py", line 32, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/core/plots/backend.py", line 17, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "reportlab/graphics/renderPDF.py", line 20, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "reportlab/graphics/shapes.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "reportlab/platypus/__init__.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "reportlab/platypus/flowables.py", line 29, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "reportlab/lib/colors.py", line 43, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "reportlab/lib/rl_accel.py", line 34, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "reportlab/lib/utils.py", line 15, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "PIL/Image.py", line 103, in <module>
ImportError: dlopen(/Applications/OpenBB Terminal/.OpenBB/PIL/_imaging.cpython-39-darwin.so, 2): Library not loaded: @loader_path/liblzma.5.dylib
  Referenced from: /Applications/OpenBB Terminal/.OpenBB/libtiff.6.dylib
  Reason: Incompatible library version: libtiff.6.dylib requires version 10.0.0 or later, but liblzma.5.dylib provides version 8.0.0
[77484] Failed to execute script 'terminal' due to unhandled exception!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Screenshots**
<img width="567" alt="Screenshot 2023-04-26 at 22 36 35" src="https://user-images.githubusercontent.com/116370283/234708413-c24a9f78-dd67-4132-b55f-ce24a9ea9f1f.png">

**Desktop (please complete the following information):**

- OS: Mac BigSur Intel i7
- Python version: 3.10.9

**Comment by deeleeramone** [comment] 2023-04-27 16:41
Is your version of Big Sur fully updated?

![image](https://user-images.githubusercontent.com/85772166/234931551-15c5990e-1550-4afa-a03f-fa3baf049a27.png)

**Comment by stephaniec2020** [comment] 2023-05-06 23:13
Thank you for the follow up, but now I've encountered another problem... should I just redownload OpenBB from scratch?

Traceback (most recent call last):
  File "terminal.py", line 44, in <module>
  File "terminal.py", line 37, in main
  File "openbb_terminal/core/session/session_controller.py", line 109, in main
  File "openbb_terminal/core/session/session_controller.py", line 75, in prompt
  File "openbb_terminal/core/session/session_controller.py", line 98, in login_and_launch
  File "openbb_terminal/core/session/session_controller.py", line 83, in launch_terminal
  File "openbb_terminal/terminal_controller.py", line 1102, in parse_args_and_run
  File "openbb_terminal/terminal_controller.py", line 1006, in main
  File "openbb_terminal/config_terminal.py", line 25, in start_plot_backend
  File "openbb_terminal/core/plots/backend.py", line 469, in plots_backend
  File "openbb_terminal/core/plots/backend.py", line 81, in __init__
  File "openbb_terminal/core/plots/backend.py", line 117, in inject_path_to_html
PermissionError: [Errno 13] Permission denied: '/Applications/OpenBB Terminal/.OpenBB/openbb_terminal/core/plots/plotly_temp.html'
[74569] Failed to execute script 'terminal' due to unhandled exception!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "openbb_terminal/core/plots/backend.py", line 428, in close
AttributeError: 'Backend' object has no attribute 'isatty'

**Comment by andrewkenreich** [comment] 2023-05-10 17:13
probably - We haven't been able to reproduce this error - on the machines I tested with a fresh install this didn't come up.

**Comment by colin99d** [comment] 2023-08-17 20:50
@stephaniec2020 did reinstalling fix your issue?

**Comment by colin99d** [comment] 2023-08-18 18:45
Im going to close this for now, let me know if the issue is still affecting you.

**Closed by colin99d** 2023-08-18 18:45 UTC
Labels: bug
