### ISSUE TITLE
[Bug] volexch bug 

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#1509] opened 2022-03-18 09:35 UTC
`python terminal.py stocks/load aal/dps/volexch`

<img width="1023" alt="Screenshot 2022-03-18 at 10 34 55" src="https://user-images.githubusercontent.com/25267873/158978025-a7e141b3-6d36-415d-a226-6a1feb2df93c.png">

**Comment by jmaslek** [comment] 2022-03-18 13:37
Hmmm.  I dont get this error.  There is a chance that you ran this while my update was running (which I do not do in a smart way)

**Comment by DidierRLopes** [comment] 2022-03-18 21:57
Just run it now and still getting it. Also had just run `poetry install`

**Comment by jmaslek** [comment] 2022-03-18 22:03
watchu get with --debug?

**Comment by DidierRLopes** [comment] 2022-03-18 22:10
```
Traceback (most recent call last):
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/terminal.py", line 855, in <module>
    main(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/terminal.py", line 797, in main
    terminal()
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/terminal.py", line 538, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 185, in switch
    getattr(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/terminal.py", line 170, in call_stocks
    self.queue = self.load_class(StocksController, self.queue)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 120, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 308, in menu
    self.queue = self.switch(an_input)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 185, in switch
    getattr(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/stocks/stocks_controller.py", line 373, in call_dps
    self.queue = self.load_class(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 120, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 308, in menu
    self.queue = self.switch(an_input)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/parent_classes.py", line 185, in switch
    getattr(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/stocks/dark_pool_shorts/dps_controller.py", line 531, in call_volexch
    nyse_view.display_short_by_exchange(
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/meghanhone/Documents/git/GamestonkTerminal/gamestonk_terminal/stocks/dark_pool_shorts/nyse_view.py", line 57, in display_short_by_exchange
    volume_by_exchange = nyse_model.get_short_data_by_exchange(ticker).sort_values(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/frame.py", line 6259, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 1779, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'Date'
~/Documents/git/
```

**Comment by jmaslek** [comment] 2022-03-18 22:23
<img width="1520" alt="Screen Shot 2022-03-18 at 6 21 53 PM" src="https://user-images.githubusercontent.com/18151143/159092229-edc0e9b3-1088-4039-8806-eb7d75b4fd36.png">

any chance your pandas is too far ahead?  I'm confuzzled

**Comment by Chavithra** [comment] 2022-04-04 13:57
Can't reproduce this.

Do you still have this issue @DidierRLopes ?

Thanks

**Comment by piiq** [comment] 2022-04-04 15:28
Unable to reproduce on the latest main. Closing as fixed

**Closed by piiq** 2022-04-04 15:28 UTC
Labels: bug
