### ISSUE TITLE
[Improve] API - `openbb.economy.fred_yield_curve(date = '2007-10-11')` : Error: 'str' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2794] opened 2022-10-11 19:54 UTC
`openbb.economy.fred_yield_curve(date = '2007-10-11')`

![Screen Shot 2022-10-11 at 12 53 30 PM](https://user-images.githubusercontent.com/85772166/195185917-43dc1ff5-0cfc-45ca-be99-56eb1d010b6b.png)

**Comment by colin99d** [comment] 2022-10-13 12:24
@minhhoang1023 I think this is a fundamental issue we need to decide for the terminal. Do we want the API to work with datetime and str interchangably, or do we expect people who use the API to know the correct data type to use? Allowing for strings will be a big refactor (and will be hard since there is no standard string for datetimes).

**Comment by colin99d** [comment] 2022-10-13 12:25
Assigning this to myself for now. But more to lead the discussion, since really this is an improvement and not a bug fix.

**Comment by jmaslek** [comment] 2022-10-13 13:08
> @minhhoang1023 I think this is a fundamental issue we need to decide for the terminal. Do we want the API to work with datetime and str interchangably, or do we expect people who use the API to know the correct data type to use? Allowing for strings will be a big refactor (and will be hard since there is no standard string for datetimes).

We should definitely make it to allow strings and make sure all documentation and examples show as "YYYY-MM-DD".

**Comment by colin99d** [comment] 2022-10-14 15:37
Ok. Didier agreed with this when I talked to him. However I am going to move this to an improvement. This is going to need to be a large terminal-wide change.

**Closed** 2023-04-18 18:55 UTC
Labels: enhancement
